apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: customer
        env:
        - name: NODE_ENV
          value: qa
