apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: customer
        image: ngpsanjaya/customer:1.0.0
        imagePullPolicy: Always
        env:
        - name: NODE_ENV
          value: qa
