apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
spec:
  template:
    spec:
      containers:
      - name: customer
        image: ngpsanjaya/customer:1.0.1
        imagePullPolicy: Always
        env:
        - name: NODE_ENV
          value: development
