apiVersion: apps/v1
kind: Deployment
metadata:
  name: store
spec:
  template:
    spec:
      containers:
      - name: store
        image: ngpsanjaya/store:1.0.0
        imagePullPolicy: Always
        env:
        - name: FLASK_ENV
          value: development
