apiVersion: apps/v1
kind: Deployment
metadata:
  name: store
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: store
        image: ngpsanjaya/store:1.0.0
        imagePullPolicy: Always
        env:
        - name: FLASK_ENV
          value: production
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
