apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: customer
        env:
        - name: NODE_ENV
          value: production
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
